FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    git curl unzip build-essential software-properties-common ripgrep fd-find \
    {% if "python" in languages %} python3 python3-pip {% endif %} \
    {% if "go" in languages %} golang {% endif %} \
    {% if "rust" in languages %} curl && curl https://sh.rustup.rs -sSf | sh -s -- -y {% endif %} \
    {% if "node" in languages %} nodejs npm {% endif %} \
    && rm -rf /var/lib/apt/lists/*

{% if nvim_config_type != "I will use VS code" %}

RUN curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.appimage \
    && chmod u+x nvim-linux-x86_64.appimage \
    && ./nvim-linux-x86_64.appimage --appimage-extract \
    && mv squashfs-root /usr/local/nvim \
    && ln -s /usr/local/nvim/usr/bin/nvim /usr/local/bin/nvim \
    && rm nvim-linux-x86_64.appimage


{% if nvim_config_type != "Custom Local Path" %}
# Install Neovim config
{%endif%}

{% if nvim_config_type == "NvChad" %}
RUN git clone https://github.com/NvChad/starter ~/.config/nvim --depth 1
{% elif nvim_config_type == "LazyVim" %}
RUN git clone https://github.com/LazyVim/starter ~/.config/nvim --depth 1
{% elif nvim_config_type == "AstroNvim" %}
RUN git clone https://github.com/AstroNvim/AstroNvim ~/.config/nvim --depth 1
{% elif nvim_config_type == "kickstart.nvim" %}
RUN git clone https://github.com/nvim-lua/kickstart.nvim ~/.config/nvim --depth 1
{% elif nvim_config_type == "Custom GitHub Repo" and custom_nvim_repo %}
RUN git clone {{ custom_nvim_repo }} ~/.config/nvim
{% endif %}

{%endif%}

WORKDIR /workspace

