FROM debian:bookworm-slim

# Create a non-root user (same UID/GID as host user)
ARG USERNAME=$USERNAME
ARG USER_UID=$USER_UID
ARG USER_GID=$USER_GID

RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
    && apt-get update && apt-get install -y sudo \
    && echo "$USERNAME ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers.d/$USERNAME

RUN apt-get update && apt-get install -y \
    git curl unzip build-essential software-properties-common ripgrep fd-find \
    {%- if "python" in languages %} python3 python3-pip \{%- endif %}
    {%- if "go" in languages %} golang \{%- endif %}
    {%- if "rust" in languages %} curl && curl https://sh.rustup.rs -sSf | sh -s -- -y \{%- endif %}
    {%- if "node" in languages %} nodejs npm {%- endif %}

{%- if nvim_config_type != "I will use VS code" %}

RUN curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.appimage \
    && chmod u+x nvim-linux-x86_64.appimage \
    && ./nvim-linux-x86_64.appimage --appimage-extract \
    && mv squashfs-root /usr/local/nvim \
    && ln -s /usr/local/nvim/usr/bin/nvim /usr/local/bin/nvim \
    && rm nvim-linux-x86_64.appimage

USER $USERNAME

{%- if nvim_config_type != "Custom Local Path" %}
# Install Neovim config
{%-endif%}

{%- if nvim_config_type == "NvChad" %}
RUN git clone https://github.com/NvChad/starter home/$USERNAME/.config/nvim --depth 1
{%- elif nvim_config_type == "LazyVim" %}
RUN git clone https://github.com/LazyVim/starter home/$USERNAME/.config/nvim --depth 1
{%- elif nvim_config_type == "AstroNvim" %}
RUN git clone https://github.com/AstroNvim/AstroNvim home/$USERNAME/.config/nvim --depth 1
{%- elif nvim_config_type == "kickstart.nvim" %}
RUN git clone https://github.com/nvim-lua/kickstart.nvim home/$USERNAME/.config/nvim --depth 1
{%- elif nvim_config_type == "Custom GitHub Repo" and custom_nvim_repo %}
RUN git clone {{ custom_nvim_repo }} home/$USERNAME/.config/nvim
{%- endif %}

RUN mkdir -p /home/$USERNAME/.local/share/ \
    && chown -R $USER_UID:$USER_GID /home/$USERNAME/.local
{%-endif%}

{%- if "haskell" in languages %}
RUN curl https://get-ghcup.haskell.org -sSf | BOOTSTRAP_HASKELL_NONINTERACTIVE=1 sh
RUN echo 'source /home/$USERNAME/.ghcup/env' >> 
{%- endif %}

WORKDIR /workspace

